install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_0.53_Linux-64bit.deb && sudo dpkg -i hugo*.deb
  - git clone https://github.com/alvarobele/BlogIC
script:
  - rm hugo*.deb
  - hugo new site sitio && cd sitio && mv data/ layouts/ static/ themes/ ../ && cd ..
  - mkdir -p sitio/content/post
  - mv BlogIC/post/* sitio/content/post/ 
  - rm sitio/config.* && mv BlogIC/config.toml sitio/
  - cd sitio
  - mv ../data/ ../layouts/ ../static/ ../themes/ . && cd themes && git clone https://github.com/nirocfz/arabica && cd ..
  - hugo -t arabica 

deploy:
  provider: pages
  local-dir: sitio
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
