install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-32bit.deb && sudo dpkg -i hugo*.deb
  - git clone https://github.com/alvarobele/BlogIC
script:
  - hugo new site sitio
  - mv BlogIC/* sitio/content/posts/ 
  - hugo

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
