install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_0.53_Linux-64bit.deb && sudo dpkg -i hugo*.deb
  - git clone https://github.com/alvarobele/BlogIC
script:
  - rm hugo*.deb
  - hugo new site sitio 
  - cd sitio
  - hugo  

deploy:
  provider: pages
  local-dir: sitio
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
